server:
  port: 9999
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.45.88:3306/db_qiuyi?characterEncoding=utf-8
    username: medicalteam
    password: medicalteam_2017
    #数据库连接池配置
    max-active: 200
    max-idle: 100
    min-idle: 50
    initial-size: 20
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    validation-query: select 1
    #每10分钟收集空闲连接，单位毫秒
    time-between-eviction-runs-millis: 600000
    #连接的最大空闲时间，单位毫秒，60分钟
    min-evictable-idle-time-millis: 3600000
    max-wait: 60000
  application:
    name: backend-information
    instance_id: 002
  thymeleaf:
    mode: LEGACYHTML5
    suffix: .html
    prefix: classpath:/templates/
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 60000
